# Generated by Django 5.2.3 on 2025-06-16 22:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0002_zumbaclass_zumbabooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='HIITClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='HIIT', max_length=100)),
                ('instructor', models.CharField(max_length=100)),
                ('start_time', models.DateTimeField()),
                ('total_vacancy', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='HIITBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_email', models.EmailField(max_length=254)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('hiit_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='fitness.hiitclass')),
            ],
        ),
    ]
