# Generated by Django 5.2.3 on 2025-06-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0003_hiitclass_hiitbooking'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Booking',
            new_name='YogaBooking',
        ),
    ]
